### ISSUE TITLE
This component hoards solaredge connection

### ISSUE THREAD

**Issue by ryanm101** [binsentsu/home-assistant-solaredge-modbus#107]
I've noticed trying to connect to solaredge (per the docs, only 1 TCP connection allowed) i get connection refused. If i disable this component then i can connect without issue. 

This component should open the connection, get data, disconnect and if it gets a connection refused subsequently it should reattempt connection at a set interval. Adding a option to toggle between the two behaviours would also be acceptable as for some this would be the only device connecting to the inverter.

**Comment by mpredfearn** [comment]
This was discussed in #82 - the optimal solution is to run a modbus proxy somewhere that maintains the single connection to the inverter, and all of your other clients connect to that.
