### ISSUE TITLE
Meter reported wrong values 

### ISSUE THREAD

**Issue by ChristophCaina** [binsentsu/home-assistant-solaredge-modbus#126]
For Long Time, the Integration of my Inverter worked well and without any issues.

But today, when I wanted to Check the Reports of the Energy usage, I've noticed the following issue in my Energy dashboard:

![Screenshot_20221205-014028](https://user-images.githubusercontent.com/26391061/205527477-bbe0b047-2716-46ad-8774-fd0c56abdb4a.png)

It appeared, that the import Meter, as Well as the Export Meter reported a wrong value for a short Period of time.

In fact, this should not happen - and the state_class total increasing should be fine - but maybe - such a wrong Report could be avoided by a Check?

**Comment by ChristophCaina** [comment]
today, I noticed the same behave again - around 18:15 ...
I could not see anything within the HA Logs.

It appears, that all import and export sensors are showing a "drop" at the same time:

![grafik](https://user-images.githubusercontent.com/26391061/205999234-a370d832-3e87-4570-b491-35789900dead.png)
![grafik](https://user-images.githubusercontent.com/26391061/205999259-192a2856-e990-44de-ae91-c41aebc0607b.png)

for me, it seems as it happens after the recent update... ?!

**Comment by dick902** [comment]
I got the same issues as you after V1.7.0 update!
I had rollback to V1.6.0 and the problem gone.
Seems this is related to the V1.7.0 refactor change.

**Comment by SgtBatten** [comment]
What are you rolling back? Can't figure out what 1.7.0 you refer to

**Comment by binsentsu** [comment]
Rolled back the validation change for now like before. We'll need to investigate this issue further to see if we can filter it.

**Comment by ChristophCaina** [comment]
updated to 1.7.1 and keeping an eye on it :)
Glad, that it became visible while running on my evaluation database :D

**Comment by TheLordVader** [comment]
Updated to 1.7.1 and no errors for 24h, just like it was before 1.7.0.

**Comment by ryanm101** [comment]
But this makes no sense.. 

Why would a zero reading not be valid?
If my inverter is not producing 0 is the valid state. 

Also changing the battery line `battery_SoC = validate(decoder.decode_32bit_float(), ">=", 0.0)` will now cause the integration to not load at all when the battery is empty.

**Comment by binsentsu** [comment]
Think problem is that 0 is also reported as 'default' value in case of connection problems etc. I think for meters and inverter the exported, imported and acenergy are total increasing numbers. Missing in these sensors the first 0.1 is less in my opinion not really a problem. As for the battery, that's maybe another thing as those zeroes are there a commonality.

**Comment by ChristophCaina** [comment]
> Think problem is that 0 is also reported as 'default' value in case of connection problems etc. 
That's probably the case - and wouldn't it make sense, that - in case of a disconnect or other 'error' the modbus data won't be read at all?
That would prevent any zero-values due to a connection issue - and, maybe even other false readings...

But yes, the fact that the total value comes back after the connection has been established indicates, that the meter is reporting total increasing values for the export / import / production kwh.
It is only the AC Power / DC Power from the Inverter and Meter that are reporting current production values - and they can report zero if there is no production.

The other sensors are production counters that should always stay with their last value and just sum up.

**Comment by SgtBatten** [comment]
> The other sensors are production counters that should always stay with their last value and just sum up.

These summation sensors should not be validated with >= 0 only >0 for that reason. Either it actually is 0 because it's brand new, or every other valid reading that it ever gets will be >0
