### ISSUE TITLE
Since upgrade to the new version spikes in energy dashboard

### ISSUE THREAD

**Issue by verstrepeng** [binsentsu/home-assistant-solaredge-modbus#128]
I've been running the previous version for about a year, without any major issues. Since the upgrade it seems randomly at certain moments, it take the complete value of the grid meter into count (not the delta). This happens 1-2 times /day, so values in energy dash are useless. From what I see, sometimes it reports a zero value and then again the correct value, resulting in counting the total again...

**Comment by tias2001** [comment]
Yes I am seeing this also

**Comment by binsentsu** [comment]
The former validation of strict > 0 has been restored in 1.7.1 to cope with these 'dropping' zero signals again.
