### ISSUE TITLE
Unable to connect inverter to Wifi

### ISSUE THREAD

**Issue by Daniel-dev22** [binsentsu/home-assistant-solaredge-modbus#145]
I'm able to switch the inverter to ap mode and connect to it and enable modbus over tcp.

However, I'm unable to get the inverter to connect to my wifi network. In the browser when it's in ap mode it just shows "Wifi NC". Solar edge support is useless. Does anyone have any ideas of how to get it to connect to a wifi network. 

I have the `SE10000H` inverter if that helps.

**Comment by ChristophCaina** [comment]
pls. check if you have the correct firmware version running on the inverter.
https://github.com/binsentsu/home-assistant-solaredge-modbus/discussions/117

You might need to contact the support from Solar Edge if Wifi is not working.

**Comment by Brutusn** [comment]
Apparently they blocked the access over WiFi from a certain firmware version. You have to connect it to a cable to be able to access it.

I have no clue why they choose to do that ¯\_(ツ)_/¯
