### ISSUE TITLE
how to enable power control without battery?

### ISSUE THREAD

**Issue by rickroetenberg** [binsentsu/home-assistant-solaredge-modbus#152]
Hi,

How can I enable to power control function without a battery? It would be nice if I can change the power control (so the output to the grid) when energy pricing is negative.

Looking forward hearing from you.

Kind regards,

Rick

**Comment by jtonk** [comment]
I'm also interested in this idea.

**Comment by jovana** [comment]
> Hi,
> 
> 
> 
> How can I enable to power control function without a battery? It would be nice if I can change the power control (so the output to the grid) when energy pricing is negative.
> 
> 
> 
> Looking forward hearing from you.
> 
> 
> 
> Kind regards,
> 
> 
> 
> Rick

Hi,

I had asked the same question in here: https://github.com/WillCodeForCats/solaredge-modbus-multi/discussions/296

**Comment by Johan-EU** [comment]
Hi,

Pull request #163 makes it possible to control the power output of an inverter. You don't need a battery.

**Comment by binsentsu** [comment]
Released in [V1.9.0](https://github.com/binsentsu/home-assistant-solaredge-modbus/releases/tag/V1.9.0) Thanks for the effort @Johan-EU
