### ISSUE TITLE
Future HA versions require key  'version' for admission of modbus as custom integration

### ISSUE THREAD

**Issue by dxxxm** [binsentsu/home-assistant-solaredge-modbus#16]
> 2021-03-06 11:05:04 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'solaredge_modbus'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'solaredge_modbus'

**Comment by binsentsu** [comment]
Thx for reporting. Will address it asap.

**Comment by binsentsu** [comment]
Fixed in 1.2.2.
