### ISSUE TITLE
Unable to change the active power limit programmatically

### ISSUE THREAD

**Issue by jydoulliez** [binsentsu/home-assistant-solaredge-modbus#167]
First of all thanks for this very useful component. I am struggling however to change the active power limit of my inverter.

When I limit the active power of my inverter via the UI (slider of the entity number.solaredge_active_power_limit) the value is taken into account by my inverter. It stays at the selected value until I change it. So in my understanding the inverter is configured correctly.

However, if I try to modify the entity state via the page Developer Tools/States (or programmatically) the value changes briefly then comes back at the value defined in the UI. So I end up with this behaviour where my script is trying to reduce the power but it keeps coming back at 100 % :

![image](https://github.com/binsentsu/home-assistant-solaredge-modbus/assets/5636009/8447bebf-7c6d-4442-ae7f-e85d628f33f8)

How is it possible to change the value programmatically without fighting the value defined in the UI ? Am I doing something wrong ?

**Comment by binsentsu** [comment]
Use an automation which calls service input_number.set_value for the power control entity id

**Comment by jydoulliez** [comment]
Thanks for your answer. I tried this service to change the value using the developer tools :

![image](https://github.com/binsentsu/home-assistant-solaredge-modbus/assets/5636009/891098bc-f10f-4d14-a20e-0e8636e010d9)

But it doesn't seem to change it (not even temporarily) and it's the only entity related to power control that I can see.

**Comment by jydoulliez** [comment]
Oops by using number.set_value instead of input_number.set_value it seems to work (makes sense). Thanks for pointing me in the right direction !
