### ISSUE TITLE
Feature Request: Get "Lifetime Data"

### ISSUE THREAD

**Issue by ChristophCaina** [binsentsu/home-assistant-solaredge-modbus#18]
HI, is it possible to get some sort of Lifetime Data like the kWh production per Hour, Day, Week, Month, year and Total?
Or how can this be acheived with the current version of this integration?

Thanks
And with best regards,
Christoph

**Comment by purcell-lab** [comment]
I seem to have lifetime data reported as (AC energy KWH), you could use 'utility meter integration' to get day/ month/ year. 

![Screenshot 2021-04-16 16 20 52](https://user-images.githubusercontent.com/79175134/114980529-f1f95400-9ecf-11eb-816f-8e2ec437574e.png)

**Comment by WillCodeForCats** [comment]
Now that Home Assistant has the Energy dashboard, just set that up.

**Comment by binsentsu** [comment]
Closing this one. As options of Utility Meter and Energy dashboard are resolving it.
