### ISSUE TITLE
Configuration through Integrationa Not possible

### ISSUE THREAD

**Issue by atze09** [binsentsu/home-assistant-solaredge-modbus#2]
Hello,
I successfully installed your component through hacs. After a restart i could Not find the configuration in Integrations.
I am on latest hassio build.
What did i wrong?
So i need to add Something to the configuration.yaml? If yes, what exactly?

**Comment by thavini** [comment]
Hi,

You need to add something like below image.


Met vriendelijke groet/kind regards

Vincent

Op wo 26 feb. 2020 06:16 schreef atze09 <notifications@github.com>:

**Comment by thavini** [comment]
![SmartSelect_20200226-062830_Home Assistant](https://user-images.githubusercontent.com/11654525/75315008-b336b380-5861-11ea-8c6d-a36490a3766e.jpg)

**Comment by binsentsu** [comment]
Hello,
After installation through hacs, check if the integration is installed under your custom_components folder. When this is the case, after a restart the integration should be visible within the 'Setup Integration' dialog (Configuration -> Integrations). There is no configuration in configuration.yaml needed.
![2020-02-27_205038](https://user-images.githubusercontent.com/3612542/75481330-285dd200-59a3-11ea-9e81-af4a1b001103.png)

**Comment by atze09** [comment]
After updating hacs, deinstall solaredge component and completely fresh install the component i can see it in the intergrations.
Can i change/check the IP Port and frequency after installation.
At the moment the of every sensor is unknown, i already restartet the inverter.
Debug is empty.

**Comment by binsentsu** [comment]
Changing IP and frequency after installation is not possible (this is at the moment the case for every home-assistant integration configured through config flow UI). But you can just remove the integration and re-add it again. If port and IP are correct and reachable the sensors should immediately update after interval has passed. If the sunspec registers are the same on all inverters it should work. I'm running SE3000HD without display on firmware 4.7.x. If you're unsure about IP/port or reachability within the network, I would advice to first test connection through a tool like https://sourceforge.net/projects/sockettest/ for example.

**Comment by atze09** [comment]
Thank you for your hellp.
It was the same issue awulf was facing. Changed to solaredge Meter and Back to non se and now it works, very Strange.

Can you explain me what is the Advantage of your custom component in comparison with erikarenhill/solaredge-modbus-hass?

**Comment by binsentsu** [comment]
Advantages:
- Configurable through UI. No yaml
- Separate sensor entities in home-assistant for each modbus key register. So no need for template sensors.
- User can disable entities in which he is not interested, through integration UI

**Comment by atze09** [comment]
> Advantages:
> 
> * Configurable through UI. No yaml
> * Separate sensor entities in home-assistant for each modbus key register. So no need for template sensors.
> * User can disable entities in which he is not interested, through integration UI

Is the Data from the external Meter also available?
Amy disadvantages?

**Comment by binsentsu** [comment]
External meter is currently not available. I only have the solaredge inverter at my place for testing. I haven't used the mentioned integration, only had a look at the code.

**Comment by atze09** [comment]
Thanks for your help and your work.
Will test both, maybe it would make Sense to merge both.

**Comment by klacol** [comment]
> first

On Windows you can also make a connection test with Powershell, like this:


```shell
Test-NetConnection -ComputerName 192.168.0.10 -Port 502

ComputerName     : 192.168.0.10
RemoteAddress    : 192.168.0.10
RemotePort       : 502
InterfaceAlias   : WLAN
SourceAddress    : 192.168.0.63
TcpTestSucceeded : True
```

This is another way to verify the IP address and the port of the inverter (in my case it is 502 and not 1502).
