### ISSUE TITLE
Feature request: support for energy module in 2021.8.0

### ISSUE THREAD

**Issue by pascalwinters** [binsentsu/home-assistant-solaredge-modbus#22]
Is it possible to add the following sensor attributes for support the new energy integration that will come in HA version 2021.8.0?

https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/

**Comment by nelbs** [comment]
I was thinking the same

**Comment by grouts112** [comment]
please…
 When I look for my solaredge sensors in the new 2021.8.0 energy monitoring, they are not listed and refers to:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by gody01** [comment]
+1

**Comment by atze09** [comment]
+1

**Comment by pdeheij** [comment]
Hope you find time to adapte to energymonitor needs.

**Comment by pascalwinters** [comment]
You can make an temp fix until the integration is fixed:
![CB232529-A8E4-42A8-9916-2B3D4FFEF2EE](https://user-images.githubusercontent.com/69316923/128346403-37e82efc-0f80-4fd2-a3c7-f286828d7caa.jpeg)

**Comment by Rep-Hueman** [comment]
What is Last rest?  homeassistant.util.dt.utc_from_times ??

**Comment by pascalwinters** [comment]
> What is Last rest? homeassistant.util.dt.utc_from_times ??

Oh sorry: homeassistant.util.dt.utc_from_timestamp(0)

**Comment by atze09** [comment]
> You can make an temp fix until the integration is fixed:
> With last reset as value: homeassistant.util.dt.utc_from_timestamp(0)
> ![CB232529-A8E4-42A8-9916-2B3D4FFEF2EE](https://user-images.githubusercontent.com/69316923/128346403-37e82efc-0f80-4fd2-a3c7-f286828d7caa.jpeg)

I already tried to fix it this way. But the entity is still not visible in der energy section. Anyone got it working

**Comment by pascalwinters** [comment]
> > You can make an temp fix until the integration is fixed:
> > With last reset as value: homeassistant.util.dt.utc_from_timestamp(0)
> > ![CB232529-A8E4-42A8-9916-2B3D4FFEF2EE](https://user-images.githubusercontent.com/69316923/128346403-37e82efc-0f80-4fd2-a3c7-f286828d7caa.jpeg)
> 
> I already tried to fix it this way. But the entity is still not visible in der energy section. Anyone got it working?

It works at my side. What’s the problem, can’t you configure the entity as solar production?

**Comment by pascalwinters** [comment]
![B323B91B-86B0-4F61-9ACB-D40821A5BF3D](https://user-images.githubusercontent.com/69316923/128409730-ba72cd3c-6c77-4f17-91b4-ea23f3ad5d20.jpeg)

**Comment by theautomation** [comment]
+1

**Comment by grouts112** [comment]
> > I already tried to fix it this way. But the entity is still not visible in der energy section. Anyone got it working?
> 
> It works at my side. What’s the problem, can’t you configure the entity as solar production?

I cannot get the workaround to work either,  
I created customization..
![image](https://user-images.githubusercontent.com/56949816/128446453-748ba6aa-69bc-4e33-9b80-47b4ab853395.png)

But when I go to add as Solar Production...  it is not listed....
![image](https://user-images.githubusercontent.com/56949816/128446574-6da36cb1-2233-42f8-a318-326717e47484.png)

**Comment by grouts112** [comment]
I thought that maybe I made an error when defining the "Last reset" as all screenshots show "Last"  with a capital 'L'
So I deleted and redefined the customization as 'last reset'  ( still shows in the GUI as 'Last reset'   but is lower case when you look in customize.yaml file
 Didn't help :-(    also tried on my test machine with same result.
 
 I have noticed it has picked it up as an attribute, when I look at the Entity....
 
![image](https://user-images.githubusercontent.com/56949816/128454682-a05b5534-859c-4b00-ac85-89d6ac4891b2.png)

any ideas why it doesn't work for some of us?  I would really love to be able to use the new Energy integration !

**Comment by grouts112** [comment]
Sorted the work around !!
 I was on the right track before with the definition of "last reset"
   you have to enter "last_reset"   !!!
   
   
![image](https://user-images.githubusercontent.com/56949816/128456847-ab416197-f48b-45a3-a278-ce77896601c8.png)

**Comment by atze09** [comment]
> Sorted the work around !!
> I was on the right track before with the definition of "last reset"
> you have to enter "last_reset" !!!
> 
> ![image](https://user-images.githubusercontent.com/56949816/128456847-ab416197-f48b-45a3-a278-ce77896601c8.png)

"last_reset" works for me. Thanks!

**Comment by membersound** [comment]
I don't get it. With modbus, I have two sensors by default:
```
sensor.solaredge_modbus
sensor.solaredge_modbus_meter_1
```

What do I have to do with them in "Customizations" in order to get the sensors up for the new HA energy integration?

**Comment by atze09** [comment]
> I don't get it. With modbus, I have two sensors by default:
> 
> ```
> sensor.solaredge_modbus
> sensor.solaredge_modbus_meter_1
> ```
> 
> What do I have to do with them in "Customizations" in order to get the sensors up for the new HA energy integration?

I think those two sensors were old config of this or another integration. First you should update to the latest version if this integration. And under HA settings there should be an optimzation point, maybe that is also not visible with older HA versions

**Comment by membersound** [comment]
My bad: I'm actually using https://github.com/erikarenhill/solaredge-modbus-hass
It it worth (or possible) to switch to this modbus integration?

**Comment by Rep-Hueman** [comment]
> > I don't get it. With modbus, I have two sensors by default:
> > ```
> > sensor.solaredge_modbus
> > sensor.solaredge_modbus_meter_1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do I have to do with them in "Customizations" in order to get the sensors up for the new HA energy integration?
> 
> I think those two sensors were old config of this or another integration. First you should update to the latest version if this integration. And under HA settings there should be an optimzation point, maybe that is also not visible with older HA versions

in --> customize.yaml

sensor.solaredge_ac_energy_kwh:
>   state_class: measurement
>   device_class: energy
>   last_reset: homeassistant.util.dt.utc_from_timestamp(0)

**Comment by binsentsu** [comment]
Hi. Latest version V1.3.0 now adds support for the energy module.
