### ISSUE TITLE
Help with the Integration

### ISSUE THREAD

**Issue by Subia75** [binsentsu/home-assistant-solaredge-modbus#25]
I need help installing the integration. 

I have a I install through HACS but after reboot of Home-Assistant, I don't see the integration then i can't be configured it
I have hassio  2021.8.5 version.
I don't understand what I'm doing wrong. 

I ask if possible help, I do not think it is a problem related to the 2021. 8release

Thank

**Comment by grouts112** [comment]
Once installed via HACS,  did you then go to Home assistant Configuration —> Integrations
And added the integration ?
HACS just installs it to HA,  you then need to add the integration.

**Comment by Subia75** [comment]
Thanks for the reply.
I solved
I didn't understand why I couldn't find the integration after a reboot.
Then I turned off the power to the raspberry and on reboot it included me in the integrations.
Sorry I could have tried before asking.
