### ISSUE TITLE
KWH -> kWh

### ISSUE THREAD

**Issue by kvandt** [binsentsu/home-assistant-solaredge-modbus#26]
Maybe nit picking, but KWH should be kWh in const.py 
` "AC_Energy_KWH": ["AC Energy KWH", "acenergy", "kWh", "mdi:solar-power"], ` should be 
` "AC_Energy_kWh": ["AC Energy kWh", "acenergy", "kWh", "mdi:solar-power"], `

**Comment by kvandt** [comment]
Created pull request for first part https://github.com/binsentsu/home-assistant-solaredge-modbus/pull/27

**Comment by binsentsu** [comment]
Released in V1.3.1, Thx for PR
