### ISSUE TITLE
modbus integration not found in HA

### ISSUE THREAD

**Issue by RemcoLeonard** [binsentsu/home-assistant-solaredge-modbus#40]
I am trying to install the modbus integration for my SolarEdge. 
After installation of the component via HACS and restart of HA modules, i cannot find the integration in the list. Only the 'official' integration. 
tried to remove the component and restart of HA, and manually checked the filesystem to clear remains of the component and rein stalling it, but no luck so far. 
Where can i look further?
Thanks!

**Comment by binsentsu** [comment]
First check if it's available in your custom component folder. If so it could be a caching problem of the UI layer in the browser which prevents showing the integration in the list. Try hard refreshing the webpage. 
Windows: ctrl + F5
Mac/Apple: Apple + R of command + R
Linux: F5

**Comment by RemcoLeonard** [comment]
> First check if it's available in your custom component folder. If so it could be a caching problem of the UI layer in the browser which prevents showing the integration in the list. Try hard refreshing the webpage.
> Windows: ctrl + F5
> Mac/Apple: Apple + R of command + R
> Linux: F5

Thanks! This has fixed my issue. I'll close this..
