### ISSUE TITLE
New feature request: Multiple inverter units and meter

### ISSUE THREAD

**Issue by julezman** [binsentsu/home-assistant-solaredge-modbus#5]
Thanks for this great HACS component.  I'd like to request two new features:

1) Enhance the component so that it can read data from multiple inverters.
2) Add enhancement to read a Wattnode\SolarEdge modbus meter attached to the inverter.  This would primarily allow users to keep track of imported and exported power from the house as well as numerous other attributes the meter records.  

Didn't know if any work was going on in this regard and happy to help via a pull if not.

**Comment by binsentsu** [comment]
Hi.
1. Reading data from multiple inverters should be possible. Just go through the integration UI configuration again for the second inverter.
2. I don't own a meter, so can't test this out myself. I think the fork of goergch /
home-assistant-solaredge-modbus includes meter implementation as far as I can see. Mayb you can check this out and test it. If it is ok, I can merge it.

**Comment by miguelrjim** [comment]
I've tested `goergch` fork and it works exporting the meter information into HA; but the way the code is set up it will fail reading the registers if there's not a meter installed so I wouldn't recommend merging its fork as it is.

**Comment by binsentsu** [comment]
@miguelrjim Thanks for the info. Are the meter and inverter hosted on the same IP address in such a setup?

**Comment by stuarts0011** [comment]
> @miguelrjim Thanks for the info. Are the meter and inverter hosted on the same IP address in such a setup?

yes,

**Comment by binsentsu** [comment]
There is currently a prerelease V1.2.0-A2 which has meter support. It would be great if it would be tested by some more people before release...

**Comment by marpi82** [comment]
> There is currently a prerelease V1.2.0-A2 which has meter support. It would be great if it would be tested by some more people before release...

I am also testinh this release, I have one meter connected to the inverter - I have not noticed any problems so far

**Comment by zeeuk** [comment]
Thank you very much! The added function works perfectly (meter)

**Comment by binsentsu** [comment]
Finally released, closing this one...
