### ISSUE TITLE
Data validation while null values in communication

### ISSUE THREAD

**Issue by gmacioso** [binsentsu/home-assistant-solaredge-modbus#50]
I experience that from time to time there are missing data from modbus meter for short period of time. They are all null values (m1), while values from inverter (ac) are normal. Seems to be some issue in communication between meter and inverter.

Anyway, would I'd be possible to add simple validation of incoming data?
If value is null, then not update entity?
Issue is important for new  Energy Management, as it creates sudden jumps in data.

On pic you can see missing data around 5:20

![Screenshot_20210926-075931_Home Assistant](https://user-images.githubusercontent.com/82769306/134796187-52dffc2c-d77f-4fcd-b3f1-7c4b35933569.jpg)

![Screenshot_20210926-083155_Home Assistant](https://user-images.githubusercontent.com/82769306/134796400-c355e579-c7b5-42f7-a437-aa32f9c0e5f6.jpg)

**Comment by gmacioso** [comment]
![Screenshot_20210926-084452_Home Assistant](https://user-images.githubusercontent.com/82769306/134796845-80f1c626-5d4a-4d5b-b3c6-b51d191b0997.jpg)

**Comment by verstrepeng** [comment]
I have the same issue.
I created utility meters in HA and use these for the energy dashboard. No problem with those.

**Comment by ChristophCaina** [comment]
can be closed
