### ISSUE TITLE
NOT AN ISSUE -QUESTION modbus polling interval

### ISSUE THREAD

**Issue by TheLordVader** [binsentsu/home-assistant-solaredge-modbus#52]
How do I change the polling interval from the inverter? I have 30 seconds now, but would like a faster update. Can't remember where to do it, and how I did when I started with this integration...

I really appreciate your work with this add-on/integration, it is essential for me in Home Assistant!

**Comment by nerfherder** [comment]
Easiest way is to remove and re-add the integration, you get prompted when it is being set up for the first time.

**Comment by cyberax17** [comment]
Would be interested in this feature too, Is there any other option?
Cheers
