### ISSUE TITLE
sensor value solaredge (AC Energy kWh)

### ISSUE THREAD

**Issue by ChristophCaina** [binsentsu/home-assistant-solaredge-modbus#63]
Hi there,

just one short question:
as far as I got, the sensor ac_energy_kwh should show the 'lifetime energy' reported from the Inverter.

For my Installation, it has the current value of: 9.318,071 kWh

Compared to the SolarEdge integration, which does pull the data from the Monitoring API, the value differes a bit:

solaredge_lifetime_energy: 9.315.445,0 Wh (9.315,445 kWh)

I just wonder, where the difference might come from... ?

**Comment by mkrasselt1** [comment]
I noticed some values are calculated versus measured.
Like amperage*volatgae*time on a time chunked order
vs kwh metering of a energy meter that constantly measures energy amounts

**Comment by ChristophCaina** [comment]
hm...
yes, I saw the same.

```
            acenergy = decoder.decode_32bit_uint()
            acenergysf = decoder.decode_16bit_uint()
            acenergy = validate(self.calculate_value(acenergy, acenergysf), ">=", 0)
```
This should be the "AC Energy" sensor, which does provide the total production kWh 

The "calculate_value" seems to be this part of the code:
```
    def calculate_value(self, value, sf):
        return value * 10 ** sf
```
so.... do I understand that correct:

acenergy = x
acenergysf = scalefactor =>y
`x * 10 ** y`

`**` is Exponentiation

I did a short "test" with some calculations...(but without knowing the exact values for acengery and acenergysf yet :-(

```
x = 1.23
y = 0.5

calc_1 = x * 10
# output = 12.3

calc_2 = calc_1 ** y
# output = 3.5071355833500366

# now the same calculation as given in the code here
calc_3 = x * 10 ** y
# output = 3.8896015220071067

# different writing for calc_2
calc_4 = (x * 10) ** y
# output = 3.5071355833500366

If I would have the exact values for acenergy and acenergysf - I could compare the different results with the values from the API ...

**Comment by ChristophCaina** [comment]
update:
I've tested this by creating a new sensor for the ACENERGY output in Raw and creating a sensor for the ACENERGYSF...

Therefore, It really seems that the RAW output is a different one than provided from the API...
so... this topic can be closed.
