### ISSUE TITLE
CONFIG FILE

### ISSUE THREAD

**Issue by josemjara** [binsentsu/home-assistant-solaredge-modbus#7]
Hi !!
Sorry, but where is the config file (path) for IP and other values??.. I installed 3 month ago and I can´t find to change this parameters and include other meters.

Thank you!!

**Comment by binsentsu** [comment]
This integration uses the new no-yaml way of configuring through UI. Editing of existing configured integration is not supported. Just remove the integration through Configuration->Integration and re-add it with changed parameters
