### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by pepsonEL** [binsentsu/home-assistant-solaredge-modbus#75]
Hi. I installed integration , enable modbus and port in my inverter and then start configuration in HA.... add IP and port and no read data. Show me entities but without data,..... In logs i have this error:

Ten błąd pochodzi z niestandardowej integracji.

```
Logger: custom_components.solaredge_modbus
Source: custom_components/solaredge_modbus/__init__.py:215
Integration: SolarEdge Modbus (documentation)
First occurred: 12:05:09 (4 occurrences)
Last logged: 12:06:39

Error reading modbus data
Traceback (most recent call last):
  File "/config/custom_components/solaredge_modbus/__init__.py", line 187, in async_refresh_modbus_data
    update_result = self.read_modbus_data()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 228, in read_modbus_data
    self.read_modbus_data_inverter()
  File "/config/custom_components/solaredge_modbus/__init__.py", line 552, in read_modbus_data_inverter
    inverter_data = self.read_holding_registers(unit=1, address=40071, count=38)
  File "/config/custom_components/solaredge_modbus/__init__.py", line 215, in read_holding_registers
    return self._client.read_holding_registers(address, count, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 108, in execute
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.4.21:1502)]
```

**Comment by KM192** [comment]
How do you connect to Inverter - by LAN or WiFi ?

**Comment by pepsonEL** [comment]
WIFI. But some days ago support from solaredge update me firmware. Before works ok. I think that update destroy communication. Modbus and port in setting inverter is enable.

**Comment by KM192** [comment]
In the newest firmware Solaredge has blocked Modbus interface via WiFi. I had the same issue with the same error. You have to downgrade (short-term) or move to cable LAN. 
And escalate that so maybe they will change this strange decision.

**Comment by pepsonEL** [comment]
But how downgrade FW ?

**Comment by KM192** [comment]
Only by contacting the support.

**Comment by pepsonEL** [comment]
But did you know when i factory reset my inverter i can connect to it by setapp without my seller which now controller my instalation ? And after reset factory i must specific setup my inverter or only create connection wifi ?

**Comment by pepsonEL** [comment]
For me better is WIFI.... becuase i dont have any router or LAN port about Inverter

**Comment by pepsonEL** [comment]
But where is LAN port in inverter ?

**Comment by KM192** [comment]
inside the case

**Comment by pepsonEL** [comment]
Support downgrade me Firmware and integration now works ok.

wt., 14 gru 2021 o 15:50 km19 ***@***.***> napisał(a):

**Comment by scottda4270** [comment]
Thanks for this. Solaredge updated my firmware too and the modbus integration stopped working two weeks ago. Could not figure it out. Just Ethernet cables the inverter and now working fine again!!! Brilliant. Thanks

**Comment by Sven-v-Beuningen** [comment]
That's interesting. I've got a solaredge inverted installed a few days ago and since then I try to get the solaredge modbus connecttion to work. I don't see any errors, but all sensors in HA show "unknown" state. 
During installation of the inverter, I also did get a firmware update.

**Comment by scottda4270** [comment]
@Sven-v-Beuningen ...do you have Modbus TCP enabled on the inverter...mine was disabled by default and i had to enable it following the instructions (i.e. by connecting to inverter using app, connecting a browser to the inverter then changing settings from there...its a well documented routine). thanks

**Comment by Sven-v-Beuningen** [comment]
@scottda4270 Yes, I also had to activate modus TCP. I think I can see some kind of communication in the logs, but I don‘t know if the data is right. There are no errors in the logs.

Best regards

Sven

**Comment by scottda4270** [comment]
Sorry @Sven-v-Beuningen , not sure i can offer you any help on this. My knowledge is pretty minimal on this so not able to offer any extended debugging assistance. Hope you manage to get it sorted soon. thanks

**Comment by Sven-v-Beuningen** [comment]
> Sorry @Sven-v-Beuningen , not sure i can offer you any help on this. My knowledge is pretty minimal on this so not able to offer any extended debugging assistance. Hope you manage to get it sorted soon. thanks

I just found the solution to the issue. I configured the integration to use multiple meters, but I just have one. I added some logs to the code, so that I could see where the issue occurs. After removing meter 2 and 3, everything works fine. 
Maybe some logging output would be helpful, because in my logs every thing was ok.

**Comment by scottda4270** [comment]
Ah ok. Glad you got it working in the end. It’s pretty good and has enabled me to create a dashboard in Grafana with everything I need. Thanks

**Comment by ChristophCaina** [comment]
@binsentsu - this could probably be closed :)
